apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "alice.k106.com"
spec:
  group: "k106.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "alice"
    singular: "alice"
    kind: "Alice"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["wonderland"]
          properties:
            wonderland:
              type: "string"
              minimum: 1
